---
title: "03-exercises: data vis ethics"
author: "Charlie Reinhardt"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

# 8.1.2 Exercises 

## Exercise 1. 

Pick 1 of the 3 examples (stand your ground, climate change, or covid cases), and summarize why that graphic is not ethical. Make sure to include the context that the graph was created in from Section 8.3 in your explanation.

I will talk about figure 8.2.1 (stand your ground). This graph is not ethical because it puts higher numbers of gun violence murders on the lower end of the y axis. This blatantly contradicts how our society learns to interpret and read graphs as children. The graph tries to suggest that Florida's "Stand Your Ground" law reduced firearm murders. Within the context when this graph was published (following the killing of Trayvon Martin), it likely swayed public opinion to view the killing of Trayvon Martin as OK, helping our society justify violence on young black men.

## Exercise 2.

Choose 2 of the 12 principles of ethical practice of data science and come up a (possibly hypothetical) scenario where each of your two chosen principles would come into play.

- 3. Build teams with diverse ideas, backgrounds, and strengths.
  When hiring for a new data science position, take care to fairly interview and consider applicants from nontraditional (or just different) backgrounds from yourself.

- 8. Present our work in ways that empower others to make better-informed decisions.
  When sharing published work on social media, ensure that the work does not mislead viewers, and that the data truly helps shed light on "things" in the data, not create perceptions that are not backed by data.
  
## Exercise 3

#### Exercise 3a. 

Find a graphic on the Internet that shows evidence that the Covid vaccine has “worked.”

Link to covid vaccine graphic that has worked: https://www.ft.com/__origami/service/image/v2/images/raw/https%3A%2F%2Fd6c748xw2pzm8.cloudfront.net%2Fprod%2F207ee5c0-a276-11eb-a6fa-3533fbee9ece-fullwidth.png?dpr=2&fit=scale-down&quality=medium&source=next&width=1260 

#### Exercise 3b. 

Find a graphic on the Internet that shows evidence that the Covid vaccine has “not worked.”

Link to covid vaccine has not worked graphic:
https://cdn.theatlantic.com/thumbor/ybG48p8arV1FTStm6br_g3yGRqw=/filters:format(png)/media/img/posts/2021/07/image_4/original.png

Maybe this graphic can argue that covid cases are still rising after lots of vaccinations? I had a hard time finding a graph that blatantly showed covid vaccines "not working"

# 8.2 Exercises

## Exercise 1. 

Which of the two visualizations better humanizes the victims of lynching? Why?

The second visualization better humanizes victoms of lynching by displaying them as individual dots. You are able to investigate and gain a little more information on each individual lynching, and it helps you remember that human lynchings are not just a data point.

## Exercise 2.

Suppose that you want to humanize the victims more in a static, non-interactive graph. Brainstorm ways that you could achieve this.

You could include links to individual names and stories, or specially label/highlight certain cases. 

## Exercise 3.

A deeper discussion of these sites appears in this paper. Read the Introduction section on TayTweets and write 3 major takeaways from this section.

a. You can't separate technology from culture: while it may be tempting, culture shapes technology and technology shapes culture and you can't escape that.

b. It is important to think about the impact that your technology can have, especially if you are publishing your technology for the open internet to see.

c. Technical schooling programs must continue (or start, or increase) to incorporate social science education into their curriculum, as situations like TayTweets or unethical graphs arise when STEM students become removed from or lose touch with issues of social justice.

## Exericse 4.

The authors of the book Data Feminism argue that “leveraging emotion” might help us better communicate with data. Read the first four paragraphs of Chapter 3 of the Data Feminism book. One example the authors use pertains to deaths from gun violence in the United States. Examine this animated chart. Explain how the chart uses emotion to convey the losses due to gun violence better than, for example, a statement that 11,356 people were killed from gun violence in 2018.

The chart quantifies the deaths in an emotional way (years of life stolen) as a result of gun violence. People can quantify an emotional relationship with a year of their personal life, or the absence of a year, in a different way than someone's premature death. It also takes special care to show each individual arc as a person, even giving the viewer the ability to read into the victim and the murder. 




