---
title: "09-intro-to-shiny"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r}
library(shiny)
```

```{r}
library(shiny)

ui <- fluidPage(
  selectInput("dataset", label = "Datset", choices = ls("package:datasets")),
  verbatimTextOutput("summary"),
  tableOutput("table")
)

server <- function(input, output, session) {
  # create a reactive expression
  dataset <- reactive({
    get(input$dataset, "package:datasets")
  })
  
  output$summary <- renderPrint( {
    # use a reactive expression by calling it like a function
    summary(dataset())
  })
  
  output$table <- renderTable({
    dataset()
  })
}

shinyApp(ui, server)
```

## 1.8 exercises

### Exercise 1

```{r}
library(shiny)

ui <- fluidPage(
  textInput("name", "What is your name?"),
  numericInput("age", "How old are you?", value = NA),
  textOutput("greeting")
)

server <- function(input, output, session) {
  output$greeting <- renderText({
    paste0("Hello ", input$name)
  })
}

shinyApp(ui, server)
```

### Exercise 2 and Exercise 3

```{r}
library(shiny)

ui <- fluidPage(
  sliderInput("x", label = "If x is", min = 1, max = 50, value = 30), 
  sliderInput("y", label = "and y is", min = 1, max = 50, value = 1),
  "then x times y is", 
  textOutput("product")
)

server <- function(input, output, session) {
  output$product <- renderText({
    input$x * input$y # grab x from input
  })
}

shinyApp(ui, server)
```

### Exercise 4
```{r}
library(shiny)

ui <- fluidPage(
  sliderInput("x", "If x is", min = 1, max = 50, value = 30),
  sliderInput("y", "and y is", min = 1, max = 50, value = 1),
  "then, (x * y) is", textOutput("product"),
  "and, (x * y) + 5 is", textOutput("product_plus5"),
  "and (x * y) + 10 is", textOutput("product_plus10")
)

server <- function(input, output, session) {
  product <- reactive({
    input$x * input$y
  })
  
  output$product <- renderText({
    product()
  })
  
  output$product_plus5 <- renderText({
    product() + 5
  })
  
  output$product_plus10 <- renderText({
    product() + 10
  })
}

shinyApp(ui, server)
```

## 9.3 SLU Majors App

```{r}

```

