---
title: "03-quiz-inclass"
author: "Charlie Reinhardt"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message= FALSE)
```

## Quiz 3 In-Class

Complete this quiz in a .Rmd file. To turn in the quiz, push both a .Rmd file and a knitted .html file to your GitHub site.

“All work presented is my own. I have not communicated with or worked with anyone else on this quiz.”

Collaboration Reminder: You may not communicate with or work with anyone else on this quiz, but you may use any of our course materials or materials on the Internet.



## Question 1 (5 points). 

Suppose you do the following:

- You go to your GitHub site and make a change to the README file (adding a sentence, for example).
- In R Studio, you update one of your .Rmd files, adding a line of code and commit the file.
- You attempt to push the new file to your GitHub site.

Once you get to the third step, you’ll get an error when you try to push. Why? What do you need to do first before you make the push in Step 3?

You need to pull the updated README from GitHub into your R Studio first! You are attempting to push an outdated version of your project to GitHub, and you are not allowed to do that (without merge requests and branches, which gets more complicated than I understand). 



## Question 2 (6 points). 

Give 2 advantages of using Git and GitHub. These must be advantages that we discussed in class (so you should not simply google “advantages of Git” and give the first two things that pop up).

- Easy for code collaboration and sharing a project between multiple team members
- Easy publishing your projects to the public (either through raw code repository or a nice github.io website)

## Question 3 (6 points). 

Choose 1 of the 12 principles of the ethical practice of data science that you think is the most difficult to execute. Give a short, possibly hypothetical, example that illustrates how that principle could be difficult to follow.

- Respect and invite fair criticism while promoting the identification and open discussion of errors, risks, and unintended consequences of our work.

This principle can be hard to follow because it is easy to get defensive about errors. Let's say you spend a ton of time to develop really cool graphic on wealth inequality, but a peer points out that you really should include another piece/dimension of data in order to better frame the issue of wealth inequality. However, your graph doesn't have the real-estate to add more information without potentially confusing your viewer, so you're tempted to not include the addition. It is difficult to put aside developing "good graphics" to include all relevant information, but additionally, including too much information just harms the viewer's ability to read the graph anyways, so then they won't be gaining any information. 

## Question 4 (6 points). 

The authors of Data Feminism argued that data scientists should “embrace emotion,” not ignore it when building visuals. State the example that the authors used to show how emotion can be used to make a visual stronger. Then, give an argument against “embracing emotion.” In other words, give an argument that data visualizations should be devoid of emotion as much as possible, even if that’s not what you believe.

The authors use the example of a gun violence graphic (phrasing gun violence deaths in terms of number of years lost, and showing the trajectory of what those lives could have been). This encourages data scientists to embrace emotions with data visualizations: the point of visualizing data is to put it into terms that a viewer can understand and internalize. If a viewer can better understand data by interpreting it through emotions, why shouldn't data scientists embrace emotions in their graphics? On the other hand, embracing emotions is a slippery slope to unfairly displaying data in an untruthful way that aligns the data with your emotions and biases. As an educated data scientist creating visualiztions, it is your duty to help inform the public to make their own decisions after looking at the data, not convince them of your opinion by using the data.

Question 5 (2 points). These two points are given for committing your .Rmd and .html files with a commit message correctly, and pushing them to your GitHub site.